export default {
    actions: {},
    mutations: {},
    state: {
        organizations: [
            { title: 'ТОО "МФО"I-CREDIT.KZ"', hide: 'block' },
            { title: 'ТОО "МФО «ФинтехФинанс"', hide: 'block' },
            { title: 'ТОО "МФО СиСиЛоун.кз"', hide: 'block' },
            { title: 'ТОО "МФО Робокэш.кз"', hide: 'block' },
            { title: 'ТОО "МФО Онлайн КазФинанс"', hide: 'block' },
            { title: 'ТОО "МФО Akshabar"', hide: 'block' },
            { title: 'ТОО "МФО Kredit Seven Kazakhstan"', hide: 'block' },
            { title: 'ТОО МФО "Credit365 Kazakhstan"', hide: 'block' },
            { title: 'ТОО МФО аФинанс', hide: 'block' },
            { title: 'ТОО «МФО «Quick Money»', hide: 'block' },
            { title: 'ТОО МФО Kaz Credit Line', hide: 'block' },
            { title: 'ТОО МФО я "Lending and Financy technologies"', hide: 'block' },
            { title: 'ТОО «Unionpart»', hide: 'block' },
            { title: 'ТОО МФО «Creditum»', hide: 'block' },
            { title: 'ТОО МФО  «SOFI FINANCE»', hide: 'block' },
            { title: 'ТОО МФО «Квику»', hide: 'block' },
            { title: 'ТОО МФО "Zanachka"', hide: 'block' },
            { title: 'ТОО «GOFINGO»', hide: 'block' },
            { title: 'ТОО «КРЕДИТ 24»', hide: 'block' },
            { title: 'ТОО «МФО «ЮНИКРЕДО»', hide: 'block' },
            { title: 'ТОО «ALTENGE»', hide: 'block' },
            { title: 'ТОО МФО «1Кредит»', hide: 'block' },
            { title: 'ТОО МФО «Деньги говорят»', hide: 'block' },
            { title: 'ТОО МФО «Смарт Финанс»', hide: 'block' },
            { title: 'ТОО МФО «365 ТЕНГЕ»', hide: 'block' },
            { title: 'ТОО «МФО «Friendly Finance Kazakhstan»', hide: 'block' },
            { title: 'ТОО МФО «TAS FINANCE GROUP»', hide: 'block' },
            { title: 'i-credit.kz', hide: 'block' },
            { title: 'moneyman.kz', hide: 'block' },
            { title: 'ccloan.kz', hide: 'block' },
            { title: 'zaimer.kz', hide: 'block' },
            { title: 'solva.kz', hide: 'block' },
            { title: '4slovo.kz', hide: 'block' },
            { title: 'creditplus.kz', hide: 'block' },
            { title: '7kredit.kz', hide: 'block' },
            { title: 'credit365.kz', hide: 'block' },
            { title: 'turbomoney.kz', hide: 'block' },
            { title: 'quickmoney.kz', hide: 'block' },
            { title: 'kclp.kz', hide: 'block' },
            { title: 'dengiclick.kz', hide: 'block' },
            { title: 'dopo.kz', hide: 'block' },
            { title: 'koke.kz', hide: 'block' },
            { title: 'tengo.kz', hide: 'block' },
            { title: 'kviku.com/kz', hide: 'block' },
            { title: 'zanachka.kz', hide: 'block' },
            { title: 'gofingo.kz', hide: 'block' },
            { title: 'Kredit24.kz', hide: 'block' },
            { title: 'gm24.kz', hide: 'block' },
            { title: 'aLTenge', hide: 'block' },
            { title: '1kredit.kz', hide: 'block' },
            { title: 'TengeDa', hide: 'block' },
            { title: 'CashU', hide: 'block' },
            { title: '365 Тенге', hide: 'block' },
            { title: 'Mycredit KZ', hide: 'block' },
            { title: 'TAS GROUP', hide: 'block' },
            { title: 'MoneyMan', hide: 'block' },
            { title: 'ccloan.kz', hide: 'block' },
            { title: 'Займер. Робот онлайн займов', hide: 'block' },
            { title: 'solva', hide: 'block' },
            { title: 'Честное слово', hide: 'block' },
            { title: 'credit plus', hide: 'block' },
            { title: 'Credit 365', hide: 'block' },
            { title: 'turbo money', hide: 'block' },
            { title: 'АКША БАР', hide: 'block' },
            { title: 'Quick money', hide: 'block' },
            { title: 'Kaz Credit Line', hide: 'block' },
            { title: 'Деньги Click', hide: 'block' },
            { title: 'До получки', hide: 'block' },
            { title: 'kviku', hide: 'block' },
            { title: 'zana4ka.kz', hide: 'block' },
            { title: 'qanat.kz', hide: 'block' },
            { title: 'forenzi.kz', hide: 'block' },
            { title: 'crezu.kz', hide: 'block' },
            { title: 'givemoney.kz', hide: 'block' },
            { title: 'CC Loan', hide: 'block' },
            { title: 'Hot Zaim', hide: 'block' },
            { title: 'Salem', hide: 'block' },
        ],
    },
    getters: {
        getOrganizations(state) {
            return state;
        }
    },
}
